services:
  - type: web
    name: codebreaker-lobby
    env: node
    region: singapore
    plan: free
    root: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
